# Generated by Django 2.0 on 2018-01-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bell',
            field=models.ManyToManyField(blank=True, to='community.Answer'),
        ),
    ]
